# Generated by Django 4.0.3 on 2022-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findbuddyuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
