# Generated by Django 4.0.3 on 2022-04-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_findbuddyuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findbuddyuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
