# Generated by Django 4.0.3 on 2022-04-09 09:32

from django.db import migrations, models
import find_buddy.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_findbuddyuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[find_buddy.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[find_buddy.common.validators.validate_only_letters]),
        ),
    ]
