# Generated by Django 4.0.3 on 2022-04-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_picture_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
    ]
