# Generated by Django 4.0.3 on 2022-04-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_dogmissingreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogmissingreport',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='dogmissingreport',
            name='reported_address',
            field=models.CharField(max_length=255, verbose_name='Report an address'),
        ),
        migrations.AlterField(
            model_name='dogmissingreport',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
    ]
