# Generated by Django 4.0.3 on 2022-04-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_alter_dogmissingreport_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogmissingreport',
            name='dog',
        ),
    ]
