# Generated by Django 4.0.3 on 2022-04-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_remove_dogmissingreport_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogmissingreport',
            name='dog',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='dog.dog'),
            preserve_default=False,
        ),
    ]
