# Generated by Django 4.0.3 on 2022-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
